-- 9. 학번이 A517178 한아름 학생의 학점 총 평점을 구하시오(반올림 소수점 한자리까지만)
SELECT ROUND(AVG(POINT), 1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10. 학과번호, 학생수(명)  출력
SELECT DEPARTMENT_NO "학과번호", COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;


-- 11. 지도 교수 배정 못받는 학생은 몇명?
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12. 학번이 A112113 김고운 학생의 년도 별 평점을 구하라
-- GROUP BY절에서 성별별 사원수 추출 가능, 함수 사용 가능
/*
SELECT SUBSTR(TERM_NO,1,4), STUDENT_NO, POINT
FROM TB_GRADE
GROUP BY SUBSTR(TERM_NO,1,4), POINT, STUDENT_NO
HAVING STUDENT_NO = 'A112113' AND SUBSTR(TERM_NO,1,4) = '2001'
ORDER BY SUBSTR(TERM_NO,1,4);
*/
-- 년도별 학점 총합
--1. HAVING절 사용해 보기
SELECT SUBSTR(TERM_NO,1,4)"년도",ROUND(AVG(POINT), 1) "년도별 평점"
FROM TB_GRADE
GROUP BY SUBSTR(TERM_NO,1,4), STUDENT_NO -- 년도와 학생을 같이 묶음
HAVING STUDENT_NO = 'A112113';

--2. WHERE + GROUP BY 사용해보기
SELECT SUBSTR(TERM_NO,1,4)"년도",ROUND(AVG(POINT), 1) "년도별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);


-- 13. 학과별 휴학생 수 

SELECT DEPARTMENT_NO " 학과코드명", COUNT(DECODE(ABSENCE_YN, 'Y', 1, NULL)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- COUNT(DECODE(ABSENCE_YN, 'Y', 1, NULL)) 의 부연설명
-- 만일 ABSENCE_YN의 값이 'Y'였을 경우 COUNT(1)이 되어 갯수를 세게 되고
--     ABSENCE_YN의 값이 'Y'가 아니였을 경우 COUNT(NULL)이 되어 갯수를 세지 않게되는 원리!!



-- 14. 동명 이인 찾기

SELECT STUDENT_NAME "동일이름", COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY STUDENT_NAME;

-- 15. 학번 A112113 김고운 학생 년도, 학기별 평점, 년도 별 누적 평점, 총 평점
SELECT SUBSTR(TERM_NO,1,4)"년도", SUBSTR(TERM_NO,5,2)"학기", ROUND(AVG(POINT),1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP (SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2))
ORDER BY "년도";




